### ISSUE TITLE
Taxonomy v3.9 might not be working properly with Kraken

### ISSUE THREAD

**Issue by miguelpmachado** [lskatz/Kalamari#14]
Hi,

I'm testing the Kalamari DB with Kraken2 and I think the [taxonomy v3.9](https://github.com/lskatz/Kalamari/tree/master/src/taxonomy_v3.9) is not working as intended (at least not working as described in the [Database formatting instructions](https://github.com/lskatz/Kalamari/blob/master/docs/DATABASES.md)):

- Following the [Kraken2 instructions](https://github.com/lskatz/Kalamari/blob/master/docs/DATABASES.md#kraken2-with-kalamari-fried-kalamari), Kraken creates the database only with 2 sequences
```text
Candidatus Korarchaeum cryptofilum	CP000968	374847
Halobacterium salinarum	AM774415	478009
```
(from the [chromosomes file](https://github.com/lskatz/Kalamari/blob/master/src/chromosomes.tsv))

- Using taxonomy [taxonomy v3.5](https://github.com/lskatz/Kalamari/tree/master/src/taxonomy_v3.5), the database is then created with 284 sequences.
- If I concatenate both taxonomy versions, one entry is added to the database: `Betacoronavirus coronavirus	MT233526	2697049`.
- If we ignore the 19 entries found in chromosomes file that don't have accession numbers (and therefore not downloaded), there are still 3 entries that are not included in Kraken's database both with taxonomy v3.5 or taxonomy v3.5+v3.9
```text
Campylobacter hyointestinalis hyointestinalis	CP015575	91352
Campylobacter hyointestinalis lawsonii	CP015575	91353
Escherichia albertii	CP024282	208961
```

- The Escherichia entry (the taxonomy id) doesn't have a matching entry in taxonomy files. I searched for that taxonomy id and it was [Influenza virus](https://www.ncbi.nlm.nih.gov/taxonomy/?term=208961%5Buid%5D). Escherichia albertii seems to be [208962](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=208962&lvl=3&lin=f&keep=1&srchmode=1&unlock). I tried to replace 208961 in the sequence header by 208962, but Kraken is still ignoring this entry (I might be missing something or doing something wrong).
- For the Campylobacter entries, different taxonomy ids use the same accession number (which might forces Kraken to not include those into the database).

My idea here is to let you know the problems I found, and try to understand how does everything work, so I could contribute and try to increase/improve the Kalamari DB.

Thanks a lot,

Best regards,

Miguel

**Comment by lskatz** [comment]
Thanks for letting me know!  I will investigate when possible.  Thank you for being so in depth and giving me easy options to follow up on :)

**Comment by lskatz** [comment]
Trying to address this in v3.9.2 with some more rigorous scripting, in branch custom-taxdump

**Comment by lskatz** [comment]
https://github.com/lskatz/Kalamari/runs/3147121557?check_suite_focus=true

It seems to have fixed it but I'm out of time for this work week.  Let me know if you get a chance to try it?  You were totally right about the Escherichia species taxid and so thank you for finding that.

**Comment by lskatz** [comment]
I think it has been fixed and I am now monitoring it with Github Actions.  Thank you for pointing it out!
