### ISSUE TITLE
A new Yersinia taxonomy change

### ISSUE THREAD

**Issue by lskatz** [lskatz/Kalamari#15]
https://twitter.com/lskatz/status/1410382288601370629

**Comment by SVN-PhD** [comment]
Forgive my newbieness, ran into the same issues as https://github.com/lskatz/Kalamari/issues/14 when using [taxonomy v3.9](https://github.com/lskatz/Kalamari/tree/master/src/taxonomy_v3.9). However, from what I understand of this tool, I added in some newly described _Yersinia_, taxid, and accessions to [Kalamari_v3.9.tsv](https://github.com/lskatz/Kalamari/blob/master/src/Kalamari_v3.9.tsv) (Should I rename it to something like v3.9.1?).

I then added in respective entries for names.dmp and nodes.dmp for the newly entered species. If I do it in taxonomy v3.9 then kraken2 seems to only report taxid 478009 when I try a test _Yersinia_ sequence. However, if I update their respective entries into names.dmp and nodes.dmp for [taxonomy v3.5](https://github.com/lskatz/Kalamari/tree/master/src/taxonomy_v3.5), then they seem to be reporting the correct taxonomy.

**Comment by lskatz** [comment]
Thank you for these updates.  I just wanted to give you my status that I am working hard on making sure that the automated tests work before addressing this.  v3.9.1 will work :)

**Comment by lskatz** [comment]
I'm sorry to do this to you but could you take a look at the taxonomy v3.9.3 and make changes to that?  And to the latest chromosomes.tsv?  I finally have the right unit testing and can look at this more clearly.  

If this is too much, then I will find time to do the appropriate diff and add in your changes.

**Comment by lskatz** [comment]
Actually I can do this.  Thank you for contributing it!
