### ISSUE TITLE
Consider adding Corynebacterium diphtheriae

### ISSUE THREAD

**Issue by kapsakcj** [lskatz/Kalamari#28]
I will try to get the nuccore accessions, taxid where available

low priority request, but would be good for identifying Diphtheria

**Comment by kapsakcj** [comment]
Trying to get in touch with the SMEs at CDC about this. Will let you know when I learn more!

**Comment by lskatz** [comment]
Bring it on and thank you for contributing!

**Comment by lskatz** [comment]
I went and looked up what NCBI had as the reference and added it <https://www.ncbi.nlm.nih.gov/datasets/taxonomy/1717>. 7a422cb
